apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map
  namespace: 45a01a92-117d-4a51-96cc-cdb6926bd6ae
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dc-metro-map
    weight: 100
status: {}
